name: 'Verify pkgdown can build and index is complete'
description: 'Verifies that `pkgdown` can build the website and that the index reference without any warnings. If warnings are present, it implies the reference contents are incomplete or contain extra entries.'
author: 'Barret Schloerke'
inputs:
  check-title:
    description: If `false` is provided, it sets silences the warning about Vignette titles not matching their entry title.
    default: ""
    required: false
runs:
  using: "composite"
  steps:
      - name: Verify reference
        if: github.event_name != 'push'
        shell: Rscript {0}
        run: |
          if ("${{inputs.check-title}}" == "false") options(rmarkdown.html_vignette.check_title = FALSE)
          pkgdown::build_site(new_process = FALSE)
          if (!require("testthat")) pak::pkg_install("testthat")
          testthat::expect_warning(
            pkgdown::build_reference_index(),
            NA
          )
