name: 'Run a locally defined script'
description: 'Runs a locally defined script if it exists. Ex: .github/shiny-workflows/NAME.R'
author: 'Barret Schloerke'
inputs:
  name:
    description: Name of script to use. This should not include the file extension.
    required: true
runs:
  using: "composite"
  steps:
    - name: Run script
      shell: bash
      run: |
        if [ -f ".github/shiny-workflows/${{ inputs.name }}.sh" ]; then
          . ".github/shiny-workflows/${{ inputs.name }}.sh"
        fi
        if [ -f ".github/shiny-workflows/${{ inputs.name }}.R" ]; then
          Rscript -e "source('.github/shiny-workflows/${{ inputs.name }}.R', echo = TRUE)"
        fi
