on:
  workflow_call:
    inputs:
      extra-packages:
        type: string
        default: ""
        required: false
      cache-version:
        type: string
        default: "1"
        required: false
      pandoc-version:
        type: string
        default: "2.7.3"
        required: false
      check-args:
        type: string
        # default: '"--run-donttest", "--no-manual", "--as-cran"'
        default: '"--no-manual", "--as-cran"'
        required: false
      install-macOS-deps:
        type: boolean
        default: false
        required: false
      macOS:
        type: string
        default: "macOS-latest"
        required: false
      windows:
        type: string
        default: "windows-latest"
        required: false
      ubuntu:
        type: string
        required: false
        # To test more versions, they must be separated by a space. Ex: `"ubuntu-18.04 ubuntu-20.04`
        default: "ubuntu-18.04"

name: R-CMD-check

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.config.outputs.config }}
    steps:
    - { name: devel,    id: devel,    uses: r-lib/actions/setup-r@v1, with: { r-version: devel,    install-r: false } }
    - { name: release,  id: release,  uses: r-lib/actions/setup-r@v1, with: { r-version: release,  install-r: false } }
    - { name: oldrel-1, id: oldrel-1, uses: r-lib/actions/setup-r@v1, with: { r-version: oldrel-1, install-r: false } }
    - { name: oldrel-2, id: oldrel-2, uses: r-lib/actions/setup-r@v1, with: { r-version: oldrel-2, install-r: false } }
    - { name: oldrel-3, id: oldrel-3, uses: r-lib/actions/setup-r@v1, with: { r-version: oldrel-3, install-r: false } }
    - { name: oldrel-4, id: oldrel-4, uses: r-lib/actions/setup-r@v1, with: { r-version: oldrel-4, install-r: false } }
    - name: Config
      id: config
      shell: bash
      run: |
        CONFIG="[";
        CONFIG="$CONFIG  {\"os\": \"${{ inputs.macOS }}\", \"r\": \"${{ steps.release.outputs.installed-r-version }}\"}";
        CONFIG="$CONFIG, {\"os\": \"${{ inputs.windows }}\", \"r\": \"${{ steps.release.outputs.installed-r-version }}\"}";
        CONFIG="$CONFIG, {\"os\": \"${{ inputs.windows }}\", \"r\": \"3.6\"}";

        # Array variable
        UBUNTU_FLAVORS=();
        # Add each ubuntu flavor as a value
        for FLAVOR in ${{ inputs.ubuntu }}
        do
          UBUNTU_FLAVORS+=("$FLAVOR");
        done

        # Get length of an array to a variable
        arrlength=${#UBUNTU_FLAVORS[@]}

        # for loop to read all values and indexes
        for (( i=0; i<${arrlength}; i++ ));
        do
          UBUNTU_FLAVOR=${UBUNTU_FLAVORS[$i]}
          # Only allow the first ubuntu flavor to have devel
          if [ "$i" == "0" ]; then
            CONFIG="$CONFIG, {\"os\": \"$UBUNTU_FLAVOR\", \"r\": \"${{ steps.devel.outputs.installed-r-version }}\", \"http-user-agent\": \"release\" }";
          fi
          CONFIG="$CONFIG, {\"os\": \"$UBUNTU_FLAVOR\", \"r\": \"${{ steps.release.outputs.installed-r-version }}\"}"

          CONFIG="$CONFIG, {\"os\": \"$UBUNTU_FLAVOR\", \"r\": \"${{ steps.oldrel-1.outputs.installed-r-version }}\"}"
          CONFIG="$CONFIG, {\"os\": \"$UBUNTU_FLAVOR\", \"r\": \"${{ steps.oldrel-2.outputs.installed-r-version }}\"}"
          CONFIG="$CONFIG, {\"os\": \"$UBUNTU_FLAVOR\", \"r\": \"${{ steps.oldrel-3.outputs.installed-r-version }}\"}"
          CONFIG="$CONFIG, {\"os\": \"$UBUNTU_FLAVOR\", \"r\": \"${{ steps.oldrel-4.outputs.installed-r-version }}\"}"
        done
        CONFIG="$CONFIG]"
        echo "$CONFIG"
        echo "'config':"
        jq <<< "$CONFIG"
        echo "::set-output name=config::$CONFIG"


  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    needs: [setup]
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJSON(needs.setup.outputs.config) }}

    env:
      GITHUB_PAT: ${{ github.token }}

    steps:
      - uses: rstudio/shiny-workflows/.github/internal/checkout@v1

      - uses: rstudio/shiny-workflows/setup-r-package@v1
        with:
          pandoc-version: ${{ inputs.pandoc-version }}
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          cache-version: ${{ inputs.cache-version }}
          needs: check
          extra-packages: |
            rcmdcheck
            ${{ inputs.extra-packages }}

      - name: Run local before-check step
        uses: rstudio/shiny-workflows/.github/internal/run-local-step@v1
        with:
          name: before-check

      - uses: r-lib/actions/check-r-package@v1
        with:
          check-dir: '"check"' # matches directory below
          args: '${{ inputs.check-args }}'

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-results
          path: "check"

      - name: Run local after-check-success step
        if: success()
        uses: rstudio/shiny-workflows/.github/internal/run-local-step@v1
        with:
          name: after-check-success
      - name: Run local after-check-failure step
        if: failure()
        uses: rstudio/shiny-workflows/.github/internal/run-local-step@v1
        with:
          name: after-check-failure
