on:
  workflow_call:
    inputs:
      extra-packages:
        type: string
        default: ""
        required: false
      cache-version:
        type: string
        default: "1"
        required: false
      pandoc-version:
        type: string
        default: "2.7.3"
        required: false
      check-title:
        type: boolean
        default: true
        required: false
name: pkgdown

jobs:
  pkgdown:

    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ github.token }}

    steps:
      - name: Checkout GitHub repo
        uses: rstudio/shiny-workflows/.github/internal/checkout@v1

      - name: Install R, system dependencies, and package dependencies
        uses: rstudio/shiny-workflows/setup-r-package@v1
        with:
          pandoc-version: ${{ inputs.pandoc-version }}
          cache-version: ${{ inputs.cache-version }}
          needs: website
          extra-packages: |
            pkgdown
            testthat
            ${{ inputs.extra-packages }}

      - name: Run 'website-build' script
        uses: rstudio/shiny-workflows/.github/internal/run-local-script@v1
        with:
          name: website-build

      # Verifies that `pkgdown` can build the website and that the index reference without any warnings.
      # If warnings are present, it implies the reference index contents are missing entries
      - name: Verify reference (PR)
        if: github.event_name != 'push'
        shell: Rscript {0}
        run: |
          if ("${{inputs.check-title}}" == "false") options(rmarkdown.html_vignette.check_title = FALSE)
          pkgdown::build_site(new_process = FALSE)
          testthat::expect_warning(
            pkgdown::build_reference_index(),
            NA
          )

      - name: Setup git (push)
        uses: rstudio/shiny-workflows/.github/internal/setup-git@v1

      - name: Build and deploy pkgdown site (push)
        if: github.event_name == 'push'
        shell: Rscript {0}
        run: |
          if ("${{inputs.check-title}}" == "false") options(rmarkdown.html_vignette.check_title = FALSE)
          pkgdown::deploy_to_branch(new_process = FALSE)
