on:
  workflow_call:
    inputs:
      extra-packages:
        type: string
        default: ""
        required: false
      cache-version:
        type: string
        default: "1"
        required: false
      pandoc-version:
        type: string
        default: "2.7.3"
        required: false
      check-title:
        type: boolean
        default: true
        required: false
    secrets:
      NETLIFY_AUTH_TOKEN:
        required: true
      NETLIFY_SITE_ID:
        required: true
name: pkgdown

jobs:
  pkgdown:

    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ github.token }}

    steps:
      - uses: rstudio/shiny-workflows/.github/internal/checkout@v1

      - uses: rstudio/shiny-workflows/setup@v1
        with:
          pandoc-version: ${{ inputs.pandoc-version }}
          cache-version: ${{ inputs.cache-version }}
          needs: website
          extra-packages: |
            pkgdown
            ${{ inputs.extra-packages }}

      - name: Run local before-build-site step
        uses: rstudio/shiny-workflows/.github/internal/run-local-step@v1
        with:
          name: before-build-site

      - name: Verify reference (PR)
        if: github.event_name != 'push'
        uses: rstudio/shiny-workflows/.github/internal/verify-pkgdown@v1


      - name: Build pkgdown site (push)
        if: github.event_name == 'push'
        shell: Rscript {0}
        run: pkgdown::build_site(new_process = FALSE)

      - name: Deploy to Netlify (push)
        if: github.event_name == 'push'
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: 'reference'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message:
            'Deploy from GHA: ${{ github.event.head_commit.message }} (${{ github.sha }})'
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: true
          alias: deploy-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
